# Solved Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [22]:
print(np.__version__)
print(np.version, end = "\n")
print(np.show_config())

1.26.4
<module 'numpy.version' from 'C:\\Users\\patil\\anaconda3\\Lib\\site-packages\\numpy\\version.py'>
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/patil/anaconda3/Library/include
    lib directory: C:/Users/patil/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1583119523984
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Informa

#### 3. Create a null vector of size 10

In [30]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array

In [32]:
arr = np.array([1, 2, 3, 4, 5])
memory_size = arr.nbytes
print(f"Memory size of an array: {memory_size} bytes")

Memory size of an array: 20 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? 

In [37]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retai

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [43]:
null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49

In [45]:
vector = np.arange(10,50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last)

In [47]:
vector  = np.array([1,2,3,4,5])
print(np.flip(vector))

[5 4 3 2 1]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [49]:
matrix = np.arange(9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [51]:
arr = np.array([1,2,0,0,4,0])
indices = np.nonzero(arr)
print(indices)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix

In [53]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values

In [57]:
arr = np.random.rand(3, 3, 3)
print(arr)

[[[0.46266852 0.75392758 0.34540254]
  [0.07371151 0.21695864 0.33632362]
  [0.42257283 0.05641596 0.8387517 ]]

 [[0.81270475 0.05010347 0.60934813]
  [0.31342958 0.4024159  0.16528981]
  [0.36163908 0.97946279 0.63009785]]

 [[0.1927298  0.78338938 0.11085501]
  [0.91452965 0.81243228 0.11974633]
  [0.97199972 0.79888364 0.45418762]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [66]:
arr = np.random.rand(10, 10)
print(arr,"\n")

min_val = np.min(arr)
print("Minimum Value = ",min_val)

max_val = np.max(arr)
print("Maximum value = ", max_val)

[[0.35772824 0.73963748 0.29176307 0.48843196 0.90644124 0.26545955
  0.63005894 0.70932297 0.73158007 0.32603599]
 [0.39251818 0.69252098 0.43159962 0.01529952 0.86923408 0.5415261
  0.58597256 0.37590587 0.68758485 0.01658021]
 [0.36603604 0.90633209 0.66470526 0.77932647 0.33345703 0.68719459
  0.15195996 0.4783163  0.31777907 0.13643012]
 [0.65678972 0.87948371 0.31537018 0.4871432  0.62970965 0.70817204
  0.05339959 0.97890756 0.84100265 0.3458975 ]
 [0.91263048 0.1221149  0.16681571 0.73020175 0.90416724 0.03724864
  0.38655802 0.13518255 0.24254802 0.47034677]
 [0.57622819 0.54678651 0.10365481 0.73067276 0.33092744 0.26459105
  0.27547535 0.40431036 0.53026693 0.80340821]
 [0.82113061 0.92849783 0.49562621 0.05798074 0.92035092 0.44352982
  0.86755005 0.45749776 0.24109384 0.17082502]
 [0.62175438 0.17580063 0.44735802 0.81729232 0.16818807 0.06536635
  0.58846454 0.46308906 0.46525031 0.26420207]
 [0.89996664 0.06790905 0.6690806  0.31084767 0.56538517 0.96855432
  0.64941699 

#### 14. Create a random vector of size 30 and find the mean value

In [74]:
vector = np.random.rand(30)
print("Vector : \n", vector,"\n")
print("Mean of Vector: ", np.mean(vector))

Vector : 
 [0.25276161 0.20128516 0.6740749  0.12161939 0.2469414  0.99062325
 0.04486241 0.2221515  0.74529525 0.43832251 0.92856203 0.50144299
 0.69612278 0.50118452 0.35054683 0.65873048 0.5645856  0.41695403
 0.76394491 0.19125799 0.46529012 0.28116025 0.00906005 0.65506548
 0.18877812 0.42119619 0.18227698 0.82126334 0.25001366 0.19533925] 

Mean of Vector:  0.4326904325391674


#### 15. Create a 2d array with 1 on the border and 0 inside

In [86]:
rows = 5
cols = 5
arr = np.zeros((rows, cols))

arr[0, :] = 1
arr[:, 0] = 1
arr[-1, :] = 1
arr[:, -1] = 1
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array?

In [90]:
existing_array = arr
new_array = np.zeros((rows+2, cols+2), dtype = existing_array.dtype)
new_array[1:-1, 1:-1] = existing_array
print(new_array)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [109]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [115]:
matrix = np.zeros((5,5), dtype = int)
np.fill_diagonal(matrix[1:],[1, 2, 3, 4])
print(matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [125]:
matrix = np.zeros((8,8), dtype = int)
matrix[1::2, ::2] = 1 #odd row and even col
matrix[::2, 1::2] = 1 # even row and odd col
print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [137]:
shape = (6,7,8)
elements = np.prod(shape)
index = 100 - 1
z = index % shape[2]
y = (index // shape[2]) % shape[1]
x = index // (shape[1] * shape[2])
print(f"The index (x,y,z) of 100th element is ({x},{y},{z})")
print("Another method using numpy fuction: ", np.unravel_index(index, shape))

The index (x,y,z) of 100th element is (1,5,3)
Another method using numpy fuction:  (1, 5, 3)
